# Generated by Django 5.2.5 on 2025-08-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_movie_review_movie_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="title",
            new_name="movie_title",
        ),
    ]
