# Generated by Django 5.2.5 on 2025-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_rating_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_title",
            field=models.CharField(max_length=200),
        ),
    ]
