# Generated by Django 5.2.5 on 2025-08-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_movie_movie_title"),
        ("users", "0003_remove_customuser_profile_picture_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.profile",
            ),
        ),
    ]
